{% set name = "dohq-artifactory" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dohq_artifactory-{{ version }}.tar.gz
  sha256: aef34d70abd95648c400bc4f9c0b20ef14067a1dd50da87e2aefacd3a0176ca6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<3.12
    - pyjwt >=2.0,<3.0
    - python-dateutil
    - requests >=2.30.0

test:
  imports:
    - dohq_artifactory
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://devopshq.github.io/artifactory/
  summary: A Python interface to Artifactory
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ewu63
    - ThomasGandilhon
