{% set name = "dohq-artifactory" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c34adaf6faede3178e5355ce6a40ae92f03a126e2b2baa122f0b60285aeee51b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<3.12
    - pyjwt >=2.0,<3.0
    - python-dateutil
    - requests >=2.30.0

test:
  imports:
    - dohq_artifactory
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://devopshq.github.io/artifactory/
  summary: A Python interface to Artifactory
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ewu63
    - ThomasGandilhon
