{% set name = "dohq-artifactory" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dohq-artifactory-{{ version }}.tar.gz
  sha256: a18d44a2e3d61194da2697573c37766e23b036baccb014fdfc8467b9feb4b98b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pyjwt ~=2.0
    - python >=3.7
    - python-dateutil
    - requests

test:
  imports:
    - dohq_artifactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://devopshq.github.io/artifactory/
  summary: A Python interface to Artifactory
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - condacircus
    - ThomasGandilhon
