schema_version: 1

context:
  name: dohq-artifactory
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 11099229572789ed38336d9ca4da2c98598a35a7cc3f183b03cdd97f10295963

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }},<3.13
    - pyjwt >=2.0,<3.0
    - python-dateutil
    - requests >=2.30.0

tests:
  - python:
      imports:
        - dohq_artifactory
      pip_check: true
      python_version: ${{ python_min }}
  - script:
      - python -m unittest discover tests/unit -v
    requirements:
      run:
        - pytest >=7.0.0
        - responses >=0.23.1

about:
  summary: A Python interface to Artifactory
  license: MIT
  license_file: LICENSE
  homepage: https://devopshq.github.io/artifactory/

extra:
  recipe-maintainers:
    - ewu63
    - ThomasGandilhon
