schema_version: 1

context:
  name: dohq-artifactory
  version: "0.10.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dohq_artifactory-${{ version }}.tar.gz
  sha256: 97076ff7316fb1ed9973dce20c6c6924959185894a6817e93e4941f21bccf53b

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }},<3.12
    - pyjwt >=2.0,<3.0
    - python-dateutil
    - requests >=2.30.0

tests:
  - python:
      imports:
        - dohq_artifactory
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A Python interface to Artifactory
  license: MIT
  license_file: LICENSE
  homepage: https://devopshq.github.io/artifactory/

extra:
  recipe-maintainers:
    - ewu63
    - ThomasGandilhon
